### ISSUE TITLE
Question: Does this support viewfinder customisation?

### ISSUE THREAD

**Issue by anniewey** [houserater/react-native-camera-ios#1]
I would like to restrict the scan area to the mask that I created instead of full screen.

**Comment by HankieCodes** [comment]
The camera component will always open as a full-screen view, but you can create a custom overlay view that renders black or red bars along the edges of the screen to appear as a crop-preview.

You'd also have to do the actual cropping of the captured image separately from this project, since this just returns what the system gave us 💁‍♂️

**Comment by anniewey** [comment]
Got it. Thanks for the insights
